config/routes.rb
TwitterEnvy::Application.routes.draw do
  
  devise_for :users
  
  resources :users, :only => [:show, :index, :update] do
    member do
      get :following, :followers, :profile_feed
    end
  end
  
  resources :posts, :only => [:create, :destroy]
  resources :reposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :searches, :only => [:index]
  
  root :to => "pages#home"
  
  match '/shared/feed', :to => "pages#feeder", :as => "feed"
  match '/auth/:provider/callback' => 'authentications#create'

  
  # SETTINGS FILTER
  match '/pages/password_settings', :to => "users#password_settings", :as => "password_settings"
  match '/pages/profile_settings', :to => "users#profile_settings", :as => "profile_settings"
  match '/pages/photo_settings', :to => "users#photo_settings", :as => "photo_settings"
  
  # FEED FILTER
  match '/pages/timeline_feed', :to => "users#timeline_feed", :as => "timeline_feed"
  match '/pages/mentions_feed', :to => "users#mentions_feed", :as => "mentions_feed"
  match '/pages/reposts_feed', :to => "users#reposts_feed", :as => "reposts_feed"

  # PROFILE FILTER
  match '/pages/following_feed', :to => "users#following_feed", :as => "following_feed"  
  match '/pages/followers_feed', :to => "users#followers_feed", :as => "followers_feed"  

  match '/contact',       :to => 'pages#contact'
  match '/featured',      :to => "users#featured"
  match '/search/:query', :to => "searches#index"
  match '/search',        :to => "searches#index"
  
  match '/people',  :to => "searches#people"

  match '/update', :to => "users#update_photo"

  match '/about', :to => "pages#about"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer(4)      not null, primary key
#  email                :string(255)     default(""), not null
#  encrypted_password   :string(128)     default(""), not null
#  password_salt        :string(255)     default(""), not null
#  reset_password_token :string(255)
#  remember_token       :string(255)
#  remember_created_at  :datetime
#  sign_in_count        :integer(4)      default(0)
#  current_sign_in_at   :datetime
#  last_sign_in_at      :datetime
#  current_sign_in_ip   :string(255)
#  last_sign_in_ip      :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  username             :string(255)
#  first_name           :string(255)
#  last_name            :string(255)
#  about                :string(255)
#  website              :string(255)
#  photo_file_name      :string(255)
#  photo_content_type   :string(255)
#  photo_file_size      :integer(4)
#  photo_updated_at     :datetime
#  relationship_status  :string(255)
#  admin                :boolean(1)      default(FALSE)
#

class User < ActiveRecord::Base
  
  has_friendly_id :username

  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :photo, :styles => { :thumb => "48x48#", :small => "128x128#"}, :processors => [:cropper],
    :content_type => 'image/jpeg/png',
    :storage => :s3,
    :bucket         => ENV['S3_BUCKET'],
    :s3_credentials => { :access_key_id     => ENV['S3_KEY'], 
                         :secret_access_key => ENV['S3_SECRET'] },
    :path => "/:style/:id/:normalized_photo_file_name"

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :username, :first_name, :last_name, :about, :website, :photo,
                  :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at,
                  :relationship_status
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  has_many :authentications
  has_many :posts,                  :dependent => :destroy
  has_many :reposts,                :dependent => :destroy
  has_many :notifications,          :dependent => :destroy
  has_many :relationships,          :dependent => :destroy,
                                    :foreign_key => "follower_id"
  has_many :reverse_relationships,  :dependent => :destroy,
                                    :foreign_key => "followed_id",
                                    :class_name => "Relationship"
  has_many :following, :through =>  :relationships, :source => :followed
  has_many :followers, :through =>  :reverse_relationships,
                        :source =>  :follower

  validates :about,     :length => { :maximum => 140 }
  validates :website, :length => { :maximum => 100 }
  validates :first_name, :presence => true, :length => { :maximum => 20 }
  validates :last_name, :presence => true, :length => {:maximum => 25 }
  
  after_update :reprocess_avatar, :if => :cropping?
  
  searchable do
    text :username
    text :first_name
    text :last_name
  end

  
  def feed
    @posts =  Post.from_users_followed_by(self)
    @reposts = Repost.from_users_followed_by(self)
    @results = @posts | @reposts
    @results.sort!{|a,b|a.updated_at <=> b.updated_at}
    @results.reverse
  end
  
  def profile_feed
    @posts = self.posts
    @reposts = Repost.where(:reposter_id => self.id)
    @results = @posts | @reposts
    @results.sort!{|a,b|a.updated_at <=> b.updated_at}
    @results.reverse
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  def cropping?
      !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
    end

    def avatar_geometry(style = :original)
      @geometry ||= {}
      @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
    end

    Paperclip.interpolates :normalized_photo_file_name do |attachment, style|
        attachment.instance.normalized_photo_file_name
      end

      def normalized_photo_file_name
        "#{self.id}-#{self.photo_file_name.gsub( /[^a-zA-Z0-9_\.]/, '_')}" 
      end

       def reprocess_avatar
          avatar.reprocess!
        end
    
      # this function allows "Edit" user without a password in Devise
        def update_with_password(params={}) 
          if params[:password].blank? 
            params.delete(:password) 
            params.delete(:password_confirmation) if params[:password_confirmation].blank? 
          end 
          update_attributes(params) 
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create]
  
  def photo_settings
    
    
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'photo_settings' }
    end
  end
  
  def profile_settings
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'profile_settings' }
    end
  end
  
  def password_settings
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'password_settings' }
    end
  end

  def index
    @title = "Whom to Follow"
    query = "AndySharkey"
    @search = User.search do
      keywords "AndySharkey"
    end
    
    @AndySharkey = @search.results
    @total_users = User.find(:all)
    @users = User.paginate(:page => params[:page])
    
   respond_to do |format|
      format.html # index.html.erb
      format.js  { render :partial => 'all_users' }
   end
      
      
          
  end
  
  def featured
    query = "AndySharkey"
    @search = User.search do
      keywords "AndySharkey"
    end
    @AndySharkey = @search.results
    
    respond_to do |format|
           format.html # index.html.erb
           format.js  { render :partial => 'featured'  }
     end
  end
  
  def strangers
    @users = User.find(:all)
    
    @following = current_user.following

    
    
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'strangers'  }
    end
  end
  
  def show
      @user = User.find(params[:id])
      @feed_items = @user.profile_feed.paginate(:page => params[:page])
    
      @title = @user.username
      @following_previews = @user.following(:limit => 6)
      @followers_previews = @user.followers(:limit => 6)
      # @notifications = current_user.notifications
  end

  def following
    @title = "Following"
    
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    
    @following_previews = @user.following(:limit => 6)
    respond_to do |format|
          format.html
          format.js  { render :partial => 'show_follow' }
    end
  end
  
  def followers
    @title = "Followers"
    
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    
    @followers_previews = @user.followers(:limit => 6)
    respond_to do |format|
          format.html
          format.js  { render :partial => 'show_follow'  }
    end
  end
  
  def profile_feed
    @user = User.find(params[:id])
    @feed_items = @user.profile_feed.paginate(:page => params[:page])

    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'profile_feed'  }
    end
  end
  
  def favorites_feed
    @feed_items = current_user.profile_feed.paginate(:page => params[:page])
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'shared/favorites_feed'  }
    end
  end
  
  def timeline_feed
    @feed_items = current_user.feed.paginate(:page => params[:page])
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'shared/feed' }
    end  
  end
  
  def mentions_feed
    query = current_user.username
    @search = Post.search do
      keywords query
    end
    @mentions = @search.results

    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'shared/mentions_feed' }
    end
  end
  
  def reposts_feed
    @reposts = Repost.where(:reposter_id => current_user)
    
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'shared/reposts_feed' }
    end
  end
  
  def searches_feed
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'shared/searches_feed' }
    end
  end
  
  def lists_feed
    respond_to do |format|
          format.html # index.html.erb
          format.js  { render :partial => 'shared/lists_feed' }
    end
  end
  
  
  
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_all_users.html.erb
<%= will_paginate %>

<%= render @users %>

<%= will_paginate %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_password_settings.html.erb
<%= form_for(current_user, :as => current_user, :url => registration_path(current_user), :html => { :method => :put }) do |f| %>


<br />
<br />

<div id="edit_password">

<span class="label_margin_right"><%= f.label :password, "New Password" %></span>
<%= f.password_field :password, :class => "round tb" %> 
</div>

<div id="edit_update">
  <p><%= f.submit "Update" %></p>
</div>
<% end %>

app/views/users/_photo_settings.html.erb
<div id="settings_container" class="round">

	<div id="settings_pool">	
			<%= form_for(current_user, :html => { :multipart => true }, 
				:as => current_user, :url => 	registration_path(current_user)) do |f| %>


			<div id="upload_photo" class="field">
			<% if current_user.photo.file? %>
				<%= image_tag current_user.photo(:small) %>
			<% else %>
				<%= show_default_small_for_user(current_user)%>
			<% end %><br />

			<%= f.label :photo, "Upload Photo" %><br/>
			<%= f.file_field :photo %>
			<p>
			</div>

			<div id="create_my_account">
			  <br />
			  <p><%= f.submit "Upload" %></p>
			</div>
			<% end %>
	
	<br />
	
</div>	<!-- end Settings Pool -->	
		</div><!-- END settings_container -->

app/views/users/_profile_settings.html.erb
<%= form_for(current_user, :as => current_user, :url => registration_path(current_user), :html => { :method => :put }) do |f| %>


<div id="edit_title_essentials">Essentials</div>
  <br />
  <div id="edit_email">
  <span class="label_margin_right"><%= f.label :email %></span>
  <%= f.text_field :email, :class => "round tb" %>
  </div>


<div id="edit_title_optional">Optional</div>
  <div id="edit_about">
  <span id="aboutfix" class="label_margin_right"><%= f.label :about %></span>
  <%= f.text_area :about, :class => "round tb", :id => "edit_about_text_area" %>
  </div>

  <div id="edit_website">
  <span class="label_margin_right"><%= f.label :website %></span>
  <%= f.text_field :website, :class => "round tb" %>
  </div>


<br />
<div id="edit_update">
  <p><%= f.submit "Update" %></p>
</div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(current_user), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/users/_sidebar_home.html.erb
<div id="sidebar_home_top">
	<span id="yourposts">
	Your Posts <%= current_user.posts.count + current_user.reposts.count %>
	</span>

	<br />


	<span  id="user_photo">

	<% if current_user.photo.file? %>
	<%= link_to (image_tag current_user.photo.url(:thumb), { 	:class =>
	 "resize_homepage"} ), user_path(current_user), :title => current_user.username %>
	<% else %>
		<%= show_default_homepage(current_user)%>
	<% end %>

	</span>

	<div id="last_post">
		<% if current_user.posts.any? %>
		  <span id="last_post_time_ago">
		    <%= link_to time_ago_in_words(current_user.posts.first.created_at)+" ago", user_path(current_user) %> 
			</span>
		<span id="last_post_content">
		    <%= wrap(linkup_mentions_and_hashtags(current_user.posts.first.content).html_safe) %>
		
		  </span>
		<% end %>
	</div>
</div>

<%= render 'shared/stats' %>

app/views/users/_strangers.html.erb
<% @users.each do |user| %>
    <% unless current_user.following?(user) %>
		<div class="feed_container">
		<% if user == current_user %>
		
		<% else %>
			<div class="feed_photo">
			<% if user.photo.file? %>
			<%= link_to image_tag user.photo(:thumb) %>
			<% else %>
				<%= show_default_thumb_for_user(user) %>
			<% end %>
			</div>
			
		    <div class="feed_user_name">
			<%= link_to "#{'@' + user.username}", user %>
			</div>
		<% end %>
		
		</div>
    <% end %>
<% end %>

app/views/users/_user.html.erb
<div class="feed_container" >
		<!-- PHOTO -->
		<span class="feed_photo">
			<% if user.photo.file? %>
			<a href="users/<%= user.username %>"><%= image_tag user.photo.url(:thumb) %></a>
			<% else %>
			<%= show_default_thumb_for_user(user) %>
			<% end %>
		</span>
		
		<!-- NAME -->
	  	<span class="feed_user_name">
	      <%= link_to "@"+user.username, user %>
	    </span>
	<br />
		<% unless user.about.nil? || user.about.empty? %>
			<span class="feed_about_user">
				<%= user.about %>
			</span>
		<% end %>
			<% if current_user.following?(user) %><br />
				<%= form_for(current_user.relationships.find_by_followed_id(user),
				             :html => { :method => :delete },
				             :remote => true) do |f| %>
				  <div class="actions">
				  	
				<input id="relationship_submit" class="myButtonLink" name="commit" type="image" value=" ">
				  
				</div>
				<% end %>
				
				
			<% elsif current_user == user %>


			    <% else %>
				<%= form_for(current_user.relationships.
				                          build(:followed_id => user.id),
				                          :remote => true) do |f| %>
				  <div><%= f.hidden_field :followed_id %></div>
					
					<input id="relationship_submit" class="myFollowButton" name="commit" type="image" value=" ">
				<% end %>
			<% end %>
		

		
		
  	</div>

app/views/users/crop.html.erb
<!-- views/users/crop.html.erb -->
<% title "Crop avatar" %>
<% content_for(:head) do %>
<%= stylesheet_link_tag "jquery.Jcrop" %>
<%= javascript_include_tag "jquery.Jcrop.min" %>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 500, 500],
    aspectRatio: 1
  });
});

function update_crop(coords) {
  var rx = 100/coords.w;
  var ry = 100/coords.h;
  $('#preview').css({
    width: Math.round(rx * <%= @user.avatar_geometry(:large).width %>) + 'px',
    height: Math.round(ry * <%= @user.avatar_geometry(:large).height %>) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = <%= @user.avatar_geometry(:original).width %> / <%= @user.avatar_geometry(:large).width %>;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>
<% end %>

<%= image_tag @user.avatar.url(:large), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @user.avatar.url(:large), :id => "preview" %>
</div>

<% form_for @user do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>

app/views/users/featured.js.erb
<%= escape_javascript render(:file => 'users/_featured.html.erb') %>

app/views/users/index.html.erb
   <title><%= @title %></title>

<div id="god">

<div id="right_side" class="round"><%= render "featured" %></div>

<div id="left_side" class="round">
<h1 id="find_people_title">Find People</h1>

Currently <%= @total_users.count %> users are registered. <br />

		<ul id="find_people_nav_list">
			<li><%= link_to "All Users", "/users/", 
					:id => "all_users_pool", :remote => true %></li>

			<li><%= link_to "Following", following_user_path(current_user), 
					:id => "following_users_pool", :remote => true %></li>

			<li><%= link_to "Followers", followers_user_path(current_user), 
					:id => "followers_users_pool", :remote => true %></li>


		</ul>

		<div id="user_pool">
			<%= will_paginate @users %>

			<%= render @users %>

			<%= will_paginate @users %>
			
		</div>

</div>

</div>

app/views/users/photo_settings.html.erb
	<%= form_for(resource, :html => { :multipart => true }, 
		:as => resource_name, :url => 	registration_path(resource_name)) do |f| %>
	<%= devise_error_messages! %>

	<div id="upload_photo" class="field">
	<% if current_user.photo.file? %>
		<%= image_tag current_user.photo(:small) %>
	<% else %>
		<%= show_default_small_for_user(current_user)%>
	<% end %><br />

	<%= f.label :photo, "Upload Photo" %><br/>
	<%= f.file_field :photo %>
	<p>
	</div>

	<div id="create_my_account">
	  <br />
	  <p><%= f.submit "Upload" %></p>
	</div>
	<% end %>

app/views/users/show.html.erb
<%= render 'sidebar_profile' %>

<%= render 'profile' %>

app/views/users/show_follow.html.erb
<%= @title %>

<% if @users.any? %>

	<%= render @users %>

<% end %>