config/routes.rb
TwitterEnvy::Application.routes.draw do
  
  devise_for :users
  
  resources :users, :only => [:show, :index, :update] do
    member do
      get :following, :followers, :profile_feed
    end
  end
  
  resources :posts, :only => [:create, :destroy]
  resources :reposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :searches, :only => [:index]
  
  root :to => "pages#home"
  
  match '/shared/feed', :to => "pages#feeder", :as => "feed"
  match '/auth/:provider/callback' => 'authentications#create'

  
  # SETTINGS FILTER
  match '/pages/password_settings', :to => "users#password_settings", :as => "password_settings"
  match '/pages/profile_settings', :to => "users#profile_settings", :as => "profile_settings"
  match '/pages/photo_settings', :to => "users#photo_settings", :as => "photo_settings"
  
  # FEED FILTER
  match '/pages/timeline_feed', :to => "users#timeline_feed", :as => "timeline_feed"
  match '/pages/mentions_feed', :to => "users#mentions_feed", :as => "mentions_feed"
  match '/pages/reposts_feed', :to => "users#reposts_feed", :as => "reposts_feed"

  # PROFILE FILTER
  match '/pages/following_feed', :to => "users#following_feed", :as => "following_feed"  
  match '/pages/followers_feed', :to => "users#followers_feed", :as => "followers_feed"  

  match '/contact',       :to => 'pages#contact'
  match '/featured',      :to => "users#featured"
  match '/search/:query', :to => "searches#index"
  match '/search',        :to => "searches#index"
  
  match '/people',  :to => "searches#people"

  match '/update', :to => "users#update_photo"

  match '/about', :to => "pages#about"
end

app/views/shared/_change_password.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>
<div id="edit_password">
<span class="label_margin_right"><%= f.label :password, "New Password" %></span>
<%= f.password_field :password, :class => "round tb" %> 	(leave blank if you don't want to change it)
</div>
<% end %>

app/views/shared/_favorites_feed.html.erb
Favorites Feed
<%= render "shared/feed" %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>

	<div id="feed_pool">
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	
	<ul id="feed_list">

	</ul>


	<%= pageless(@feed_items.total_pages, feed_path, "#feed_pool") %>
	</div>
<% end %> 

app/views/shared/_feed_item.html.erb
<% if feed_item.is_a?(Repost) %>
 
<!-- Don't show reposts in feed of others who repost you -->
<% unless feed_item.poster == current_user %>

<div class="repost_container" class="feed_item" class="block">
	
	<!-- REPOST PICTURE -->
	<div class="repost_tag">
	<%= image_tag "../images/repost_tag.png"%>
	</div>

	<div class="repost_content">
		<!-- PHOTO -->
		<div class="repost_photo">
		<% if feed_item.poster.photo.file? %>
		<%= image_tag feed_item.poster.photo.url(:thumb) %>
		<% else %>
		<%= show_default_thumb_for_user(feed_item.poster)%>
		<% end %>
		</div>

	
    	<div class="feed_item_right_side">
			<!-- USERNAME -->
			<div class="feed_user_name">
			<%= link_to feed_item.poster.username, feed_item.poster %>
			<span class="full_name"><%= "#{feed_item.poster.first_name} #{feed_item.poster.last_name}" %> <%= image_tag "../images/repost.png" %> <%= feed_item.reposter.username %></span>
			</div>
	
			<!-- POST -->
			<span class="repost_text">
			<%= wrap_text(linkup_mentions_and_hashtags(feed_item.content).html_safe) %>
			</span>
			<br />
			
			<!-- TIMESTAMP -->
			<div class="feed_timestamp_container">
				<span class="timestamp">
				<%= distance_of_time_in_words(feed_item.created_at, Time.now) %> ago.
				</span>
			</div>
		</div>
		<div class="feed_links_container" class="feed_links">
			<ul class="feed_links_list">
			<li>
			  <%= image_tag "../images/reply.png" %>
	 		<span class="reply"><%= link_to "Reply" %></span>
			</li>
			<li>
			  <%= image_tag "../images/trash.png" %>
			<%= link_to "delete", feed_item, :method => :delete, :confirm => "You sure?",
			:title => feed_item.content %>
			</li>
			</ul>
		</div>

	


	</div>
	
</div>
<% end %>
<% end %>


<% unless feed_item.nil? || feed_item.is_a?(Repost) %>
	<div class="feed_container feed_item block" id="<%= feed_item.id %>">


	<!-- PHOTO -->
	<div class="feed_photo">
	<% if feed_item.user.photo.file? %>
	<%= image_tag feed_item.user.photo.url(:thumb) %>
	<% else %> 
	<%= show_default_thumb_for_user(feed_item.user) %>
	<% end %>
	</div>

	
	<div class="feed_item_right_side">
			<!-- USERNAME -->
			<div class="feed_user_name">
			<%= link_to feed_item.user.username, feed_item.user %>
			<span class="full_name"><%= "#{feed_item.user.first_name} #{feed_item.user.last_name}" %></span>
			</div>

	
			<!-- POST -->
			<div class="post_content">
			<%= wrap_text(linkup_mentions_and_hashtags(feed_item.content).html_safe) %>
			</div>

			<!-- TIMESTAMP -->
			<div class="feed_timestamp_container">
				<span class="timestamp">
				<%= link_to distance_of_time_in_words(feed_item.created_at, Time.now)+" ago"%> 
				</span>
		
			</div>
	</div><!-- END feed_item_right_side -->
	
	<% unless feed_item.user == current_user %>
	<div class="feed_links_container" class="feed_links">
		<ul class="feed_links_list">
			<li>
			  <%= image_tag "../images/favorite.png" %>
			  <%= link_to "Favorite" %>
			</li>
			<li>
			  <%= image_tag "../images/repost.png" %>
			<span class="repost_button">
			<%= form_for(current_user.reposts.
			             build(:content => feed_item.content, 
							   :poster_id => feed_item.user.id,
							   :reposter_id => current_user.id),
			                   :remote => true) do |f| %>
			  <div><%= f.hidden_field :poster_id %></div>
			  <div><%= f.hidden_field :reposter_id %></div>
			  <div><%= f.hidden_field :content %></div>
			  <div class="actions"><%= link_to 'Repost', "#", :onclick=>"$('.new_repost').submit()" %></div>

			<% end %>
			</span>
			</li>
			<li>
			  <%= image_tag "../images/reply.png" %>
			   <span class="reply"><%= link_to "Reply" %></span>
			</li>
		</ul>
	</div>
	
	<% else %>
	<div class="feed_links_container" class="feed_links">
		<ul class="feed_links_list">
		<li>
		  <%= image_tag "../images/favorite.png" %>
		  <%= link_to "Favorite", :class => "feed_link_favorite" %>
		</li>
		<li>
		  <%= image_tag "../images/reply.png" %>
 		<span class="reply"><%= link_to "Reply" %></span>
		</li>
		<li>
		  <%= image_tag "../images/trash.png" %>
		<%= link_to "delete", feed_item, :method => :delete, :confirm => "You sure?",
		:title => feed_item.content %>
		</li>
		</ul>
	</div>
	<% end %>
	
</div><!-- end feed_container -->

<% end %>

app/views/shared/_followers_feed.html.erb
Followers Feed
<%= render "shared/feed" %>

app/views/shared/_following_feed.html.erb
Following Feed
<%= render "shared/feed" %>

app/views/shared/_mentions_feed.html.erb
<div class="filter_title"><h1 class="feed_title_color">
	Posts mentioning @<%= current_user.username %>
</h1></div>
<% unless @mentions.nil? %>
		
	<% @mentions.each do |mention| %>

<div class="feed_container" class="mention">

	<!-- PHOTO -->
	<div class="feed_photo">
	<% if mention.user.photo.file? %>
	<%= image_tag mention.user.photo.url(:thumb) %>
	<% else %> 
	<%= show_default_thumb_for_user(mention.user) %>
	<% end %>
	</div>
	
	<div class="mention_right_side">
			<!-- USERNAME -->
			<div class="feed_user_name">
			<%= link_to mention.user.username, mention.user %>
			<span class="full_name"><%= "#{mention.user.first_name} #{mention.user.last_name}" %></span>
			</div>

	
			<!-- POST -->
			<%= wrap_text(linkup_mentions_and_hashtags(mention.content).html_safe) %>
			<br />
			<!-- TIMESTAMP -->
			<div class="feed_timestamp_container">
				<span class="timestamp">
				<%= distance_of_time_in_words(mention.created_at, Time.now) %> ago 
				</span>
		
			</div>
	</div><!-- END mention_right_side -->
	
	<% unless mention.user == current_user %>
	<div class="feed_links_container" class="feed_links">
		<ul class="feed_links_list">
			<li>
			  <%= image_tag "../images/favorite.png" %>
			  <%= link_to "Favorite" %>
			</li>
			<li>
			  <%= image_tag "../images/repost.png" %>
			<span class="repost_button">
			<%= form_for(current_user.reposts.
			             build(:content => mention.content, 
							   :poster_id => mention.user.id,
							   :reposter_id => current_user.id),
			                   :remote => true) do |f| %>
			  <div><%= f.hidden_field :poster_id %></div>
			  <div><%= f.hidden_field :reposter_id %></div>
			  <div><%= f.hidden_field :content %></div>
			  <div class="actions"><%= link_to 'Repost', "#", :onclick=>"$('.new_repost').submit()" %></div>

			<% end %>
			</span>
			</li>
			<li>
			  <%= image_tag "../images/reply.png" %>
			   <span class="reply"><%= link_to "Reply" %></span>
			</li>
		</ul>
	</div>
	<% else %>
	<div class="feed_links_container" class="feed_links">
		<ul class="feed_links_list">
		<li>
		  <%= image_tag "../images/favorite.png" %>
		  <%= link_to "Favorite", :class => "feed_link_favorite" %>
		</li>
		<li>
		  <%= image_tag "../images/reply.png" %>
 		<span class="reply"><%= link_to "Reply" %></span>
		</li>
		<li>
		  <%= image_tag "../images/trash.png" %>
		<%= link_to "delete", mention, :method => :delete, :confirm => "You sure?",
		:title => mention.content %>
		</li>
		</ul>
	</div>
	<% end %>
</div><!-- end feed_container -->
<% end %>
<% end %>

<div id="results" class="results">
	
</div>

app/views/shared/_post_form.html.erb
<div id="post_title">What's happening?</div>
<div id="form_box">
	  <%= form_for(@post) do |f| %>
	  <%= render 'shared/error_messages', :object => f.object %>


		  <div id="textbox" class="tb">
			<%= f.text_area :content, :id => "post_textarea" %>
		  </div>

	
	  <div id="post_button" class="post_button">
		<%= f.submit "Post", :class => "button", :id=>"button", :remote => true %>
	  </div>

	  <div id="post_geolocation">
	  <span class="geolocation_link"><%= image_tag "target.png" %> <%= link_to "Add your location" %></span>
	<span class="user_geolocation">	<%= "#{@location[:city]}, #{@location[:region_name]}" %> <%= link_to "x" %></span> <br />
	  </div>
	
	<% end %>
</div>

app/views/shared/_relationship_stats.html.erb
<div id="stats_following_followers">
<div id="following_box">
<span id="following_stat">
<%= link_to "Following #{@user.following.count}", user_path(@user) %><br />
</span>

<span id="suggested_user">

<% unless @following_previews.nil? || @following_previews.empty? %>

<% following_count = @following_previews.count %>
<% i = 0 %>
<% while i < following_count && i < 7 %>
<span class="list_photo">
<% if @following_previews[i].photo.file? %>

<%= link_to (image_tag @following_previews[i].photo.url(:thumb), :class => "resizeme"),
 			 @following_previews[i], :class => "phototip resizeme", 
									 :title =>  @following_previews[i].username %>
<% else %>
<% user = @following_previews[i] %>
<%= link_to show_default_tiny_for_user(user),
 			 user, :class => "phototip resizeme", 
				   :title =>  user.username %>

<% end %>
</span>
<% i = i+1 %>
<% end %>
<% end %>


</span>


</div>


<div id="followers_box">
<span id="followers_stat">

<%= link_to "Followers #{@user.followers.count}", user_path(@user) %>
<br />

</span>
<% unless @followers_previews.nil? || @followers_previews.empty? %>
	<% followers_count = @followers_previews.count %>
	<% i = 0 %>
	<% while i < followers_count && i < 7 %>
		<span class="list_photo">
		<% if @followers_previews[i].photo.file? %>
			<%= link_to (image_tag @followers_previews[i].photo.url(:thumb), :class => "resizeme"), 
			 @followers_previews[i] , :class => "phototip", 
									  :title =>  @followers_previews[i].username %>

		<% else %>
		<%= link_to show_default_tiny_for_user(@followers_previews[i]),
		 @followers_previews[i] , :class => "phototip", 
								  :title =>  @followers_previews[i].username %>
		<% end %>
		
	<% i = i+1 %>
	<% end %>
<% end %>
</span>


</div>
</div>

app/views/shared/_reposts_feed.html.erb
<div class="filter_title"><h1 class="feed_title_color">Reposts by you</h1></div>
<% unless @reposts.nil? %>
	<% @reposts.each do |repost| %>

	<!-- Don't show reposts in feed of others who repost you -->
	<% unless repost.poster == current_user %>

	<div class="repost_container" class="feed_item">

		<!-- REPOST PICTURE -->
		<div class="repost_tag">
		<%= image_tag "../images/repost_tag.png"%>
		</div>


		<div class="repost_content">
		<!-- PHOTO -->
		<div class="repost_photo">
		<% if repost.poster.photo.file? %>
		<%= image_tag repost.poster.photo.url(:thumb) %>
		<% else %>
		<%= show_default_thumb_for_user(repost.poster)%>
		<% end %>
		</div>


	    <div class="feed_item_right_side_repost">
				<!-- USERNAME -->
				<div class="feed_user_name">
				<%= link_to "@"+repost.poster.username, repost.poster %>
				<span class="full_name"><%= "#{repost.poster.first_name} #{repost.poster.last_name}" %> <%= image_tag "../images/repost.png" %> <%= repost.reposter.username %></span>
				</div>

				<!-- POST -->
				<span class="repost_text">
				<%= wrap_text(linkup_mentions_and_hashtags(repost.content).html_safe) %>
				</span>
				<br />

				<!-- TIMESTAMP -->
				<div class="feed_timestamp_container">
					<span class="timestamp">
					<%= distance_of_time_in_words(repost.created_at, Time.now) %> ago.
					</span>
				</div>
		</div>



		<div class="feed_links_container" class="feed_links">
			<ul class="feed_links_list">

			<li>
			  <%= image_tag "../images/reply.png" %>
	 		<span class="reply"><%= link_to "Reply" %></span>
			</li>
			<li>
			  <%= image_tag "../images/trash.png" %>
			<%= link_to "delete", repost, :method => :delete, :confirm => "You sure?",
			:title => repost.content %>
			</li>
			</ul>
		</div>
		</div>

	</div>
	
		

		<% end %>
	<% end %>
<% end %>

app/views/shared/_searches_feed.html.erb
<div class="filter_title"><h1 class="feed_title_color">Searches by you</h1></div>

app/views/shared/_setting_profile.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>


  <div id="settings_location">
  <span id="aboutfix" class="label_margin_right"><%= f.label :city, "Location" %></span>
  <%= f.text_field :city, :class => "round tb" %>
  </div>



  <div id="edit_website">
  <span class="label_margin_right"><%= f.label :website, "Web" %></span>
  <%= f.text_field :website, :class => "round tb" %>
  </div>


  <div id="edit_about">
  <span id="aboutfix" class="label_margin_right"><%= f.label :about, "Bio" %></span>
  <%= f.text_area :about, :class => "round tb", :id => "edit_about_text_area" %>
  </div>


<br />
<div id="edit_update">
  <p><%= f.submit "Save" %></p>
</div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<%= render 'shared/relationship_stats' %>

<div id="sidebar_middle_container">
<%= render 'shared/trending' %>
<%= render 'shared/suggestions' %>
</div>

<div id="links_container">
<%= render 'users/links' %>
</div>

app/views/shared/_suggestions.html.erb
<div id="who_to_follow">
  <div id="who_to_follow_title">Who to follow</div>
  	  <div id="suggestions_title">Suggestions for you <%= link_to "view all", users_path %></div>
  <div id="suggestion_container">

    <% i = 0 %>

	<% unless @suggestions.nil? %>
	<% @suggestions.each do |s| %>
	  <% break if i > 3 %>
	  <% if !current_user.following?(s) && current_user != s  %>

		    <div id="suggestion">
	  		  <span id="suggestion_photo">
			  <% if s.photo.file? %>
			  <%= link_to (image_tag s.photo.url(:thumb), :class => "resize_suggestion"), user_path(s) %>
			  <% else %>
				<%= link_to show_default_suggestion(s), user_path(s) %>
			  <% end %>
			  </span>
			
			<ul id="suggestions_list">
			<div class="suggested_user">
 			<li><%= link_to "#{s.username}", "users/"+s.username %></li>
			</div>
			
			<li><div class="actions follow_button"><%= link_to 'Follow', "#", :onclick=>"$('.new_relationship').submit()", :remote => :true %></div>
			</li>
			</ul>
  			<br />
			<div class="suggested_user_fullname"><%= "#{s.first_name} #{s.last_name}"%></div>
	          <div id="follow_form">
			  <%= form_for(current_user.relationships.
			               build(:followed_id => s.id),
			                     :remote => true) do |f| %>
			  <div><%= f.hidden_field :followed_id %></div>
			


			  <% end %>
			  </div> <!-- END follow_form -->
		</div> <!-- END suggestion -->
			<% i = i + 1%>

	  <% else %>
	
	  <% end %> <!-- END break if i > 3 -->
	<% end %> <!-- END @suggestions.each -->
	<% end %>
	
	<%= link_to "Refresh suggestions", :onclick =>"$('suggestion_container').load('/pages/home')", :remoate => :true %><br />
	<%= link_to "Browse Interests", users_path %>
	<span id="find_friends_link"><%= link_to "Find friends", users_path %></span>
</div> <!-- END suggestion_container -->

</div> <!-- END who_to_follow -->