config/routes.rb
TwitterEnvy::Application.routes.draw do
  
  devise_for :users
  
  resources :users, :only => [:show, :index, :update] do
    member do
      get :following, :followers, :profile_feed
    end
  end
  
  resources :posts, :only => [:create, :destroy]
  resources :reposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :searches, :only => [:index]
  
  root :to => "pages#home"
  
  match '/shared/feed', :to => "pages#feeder", :as => "feed"
  match '/auth/:provider/callback' => 'authentications#create'

  
  # SETTINGS FILTER
  match '/pages/password_settings', :to => "users#password_settings", :as => "password_settings"
  match '/pages/profile_settings', :to => "users#profile_settings", :as => "profile_settings"
  match '/pages/photo_settings', :to => "users#photo_settings", :as => "photo_settings"
  
  # FEED FILTER
  match '/pages/timeline_feed', :to => "users#timeline_feed", :as => "timeline_feed"
  match '/pages/mentions_feed', :to => "users#mentions_feed", :as => "mentions_feed"
  match '/pages/reposts_feed', :to => "users#reposts_feed", :as => "reposts_feed"

  # PROFILE FILTER
  match '/pages/following_feed', :to => "users#following_feed", :as => "following_feed"  
  match '/pages/followers_feed', :to => "users#followers_feed", :as => "followers_feed"  

  match '/contact',       :to => 'pages#contact'
  match '/featured',      :to => "users#featured"
  match '/search/:query', :to => "searches#index"
  match '/search',        :to => "searches#index"
  
  match '/people',  :to => "searches#people"

  match '/update', :to => "users#update_photo"

  match '/about', :to => "pages#about"
end

app/views/layouts/_header.html.erb
<header>
  <div id="menu">
		<div id="movingmenu">
		    <ul id="mainmenu">
			  <li><div id="logo"><%= link_to logo, root_path %></div></li>
						<% if user_signed_in? %>
			<li>
				
			<form accept-charset="UTF-8" action="/searches">
			<%= text_field_tag "q", params[:q], :class => "tb round" %>
			<input id="search_submit" name="commit" type="submit" value="Search">
			</form>
			</li>
			  <li class="<%= "highlighted" if params[:controller] == "pages" && params[:action] == "home"%>"><%= link_to "Home", root_path %></li>

			  <li class="<%= "highlighted" if params[:controller] == "users" &&   params[:action] == "show"%>"><%= link_to "Profile", current_user %></li>
			  <li class="<%= "highlighted" if params[:controller] == "users"&&   params[:action] == "index" %>"><%= link_to "Whom to Follow", users_path %></li>
			  <li id="about_this_site"class="<%= "highlighted" if params[:controller] == "pages"&&   params[:action] == "about" %>"><%= link_to "About this Site", about_path %></li>
			</ul>




			
			
			
			
			<ul id="jsddm">
			<li>
				<span id="menupic">
				<% if current_user.photo.file? %>
					<%= image_tag current_user.photo.url(:thumb), :class => "headerpic" %>
				<% else %>
					<%= show_menu_pic(current_user) %>
				<% end %>
				</span>
			<%= link_to current_user.username %>
				<ul id="submenu">
					<li><%= link_to "Settings", edit_user_registration_path %></li>
					<li><%= link_to "Help" %></li>
					<li><%= link_to "Sign Out", destroy_user_session_path %></li>
				</ul>
			</li>
			</ul>
			
			
			
			
			
			
			
			
			
			<% else %>

			<div id="menu2"><div class="relative">
			  <a href="/demos" title="Sign In" id="dd2" class="dropdown" rel="dropdown2" style="width:170px;text-decoration:none;"><span>Sign In</span></a>
			  <div id="dropdown2" class="dropdown-menu">
				
				
				<%= form_for(:user, :url => user_session_path) do |f| %>
				  Username
				  <%= f.text_field :username, :id => "uname", :title => "Username", :class => "tb" %>
				  Password
				  <%= f.password_field :password, :class => "tb" %><br />
				  
				  <%= f.check_box :remember_me, :class => "floatleft" %>
				  <%= f.label :remember_me %>
				  <%= f.submit 'Sign in', :class => "floatright" %><br /><br />

				<% end %>
				
				
				
				
				
				
				
				
			  </div>
			</div></div>
			
			
			
			
			
			
			
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		    <% end %>
      
 
	   </div>

 </div>

</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'twitterenvy', :media => 'screen' %>
<%= stylesheet_link_tag 'jquery.Jcrop', :media => 'screen' %>

<%= stylesheet_link_tag 'css3buttons', :media => 'screen' %>
<%= stylesheet_link_tag 'tipTip', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <!-- PROVIDES VERIFICATION FOR GOOGLE -->
  <meta name="google-site-verification" content="Lh9385gJQysy27O50rJ3wVQSHsv-O5AUPbNidla3-F4" />

  <title><%= @title %></title>

  <%= render 'layouts/stylesheets' %>
  
<%= javascript_include_tag "jquery.js", "rails.js", "application.js", "charCount.js", "jquery.tipTip.minified", "jquery.textareaCounter.plugin.js", "jquery.ae.image.resize", "jquery.clickmenu.pack", "jquery.clickmenu", "jquery.clickmenu.js", "jquery.clickmenu.pack.js", "jquery.pageless.js" %>
  
<%= csrf_meta_tag %>

</head>
<body>

  <div class="container">

	<%= render 'layouts/header' %>
		
	<section>
	<div id="god">
	<%= yield %>
	</div>
	</section>

	<div class="whitetext"><%= debug(params) if Rails.env.development? %>
  </div>


</body>
</html>